name: FoundationModels CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Select Xcode Version
      #   run: sudo xcode-select -s /Applications/Xcode_26.app/Contents/Developer

      - name: Build
        run: swift build -c release --arch arm64

      - name: Package Binary
        run: |
          cd .build/arm64-apple-macosx/release
          zip -r ../../../AppleIntelligenceApi.zip AppleIntelligenceApi

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-artifact
          path: .build/arm64-apple-macosx/release/AppleIntelligenceApi
